// ebtAvailabilityMockData.v0.js
// Synthetic / PII-altered demo data only.

export const rawCaseRows = [
  {
    id: "raw-001",
    caseGroupId: "case-001",
    caseName: "SANTOS, MARIANA INF (LOPEZ, ELENA)",
    pca: "08A",
    calendarCall: "01/14/2026",
    cm: "PB",
    la: "ABC",
    ta: "RBN",
    synopsysOriginal: `ebt of Dr. Alan Mercer busted 5/19/26 need new date
Already deposed:
(1) Plaintiff over two days
(2) Dr. Victoria Hale
(3) North County Medical Center witness
PB emailed OPA 5/19 for new dates no response yet
need follow-up 5/23/26`,
    defs: "DR. ALAN MERCER, DR. VICTORIA HALE, NORTH COUNTY MEDICAL CENTER, RIVERDALE WOMEN'S HEALTH GROUP, P.C.",
    venue: "Queens",
    nextConf: "06/18/2026",
    div: "MM-BI",
    source: "Synthetic Demo",
    reviewStatus: "AI Pending Review",
  },
  {
    id: "raw-002",
    caseGroupId: "case-001",
    caseName: "SANTOS, MARIANA INF (LOPEZ, ELENA)",
    pca: "08A",
    calendarCall: "01/14/2026",
    cm: "PB",
    la: "ABC",
    ta: "RBN",
    synopsysOriginal: `same case different defendant row
OPA says witness may be unavailable until June but no firm dates
Plaintiff EBT completed already
need to confirm if institutional witness still needed before next conference`,
    defs: "RIVERDALE WOMEN'S HEALTH GROUP, P.C., NORTH COUNTY FACULTY PRACTICE, NORTH COUNTY MEDICAL CENTER RISK GROUP",
    venue: "Queens",
    nextConf: "06/18/2026",
    div: "MM-BI",
    source: "Synthetic Demo",
    reviewStatus: "AI Pending Review",
  },
  {
    id: "raw-003",
    caseGroupId: "case-002",
    caseName: "PARKER, JORDAN (PARKER, LENA INF)",
    pca: "08F",
    calendarCall: "02/04/2026",
    cm: "JKL",
    la: "MTR",
    ta: "SND",
    synopsysOriginal: `Firm P EBT day 2 5/21/26
Dr. Iris Conway firm 6/9/26
All dates firm per order no adjournment without court permission
Completed:
P day 1 4/10/26
Need confirm zoom/reporter by 5/20`,
    defs: "DR. IRIS CONWAY, SOUTH BAY MEDICAL CENTER, BROOK PARK OB/GYN, P.C.",
    venue: "Nassau",
    nextConf: "06/10/2026",
    div: "MM-BI",
    source: "Synthetic Demo",
    reviewStatus: "AI Pending Review",
  },
];

export const caseGroups = [
  {
    id: "case-001",
    caseName: "SANTOS, MARIANA INF (LOPEZ, ELENA)",
    normalizedCaseName: "SANTOS, MARIANA INF",
    pca: "08A",
    venue: "Queens",
    calendarCall: "01/14/2026",
    cm: "PB",
    la: "ABC",
    ta: "RBN",
    nextConf: "06/18/2026",
    div: "MM-BI",
    rawRowIds: ["raw-001", "raw-002"],
    trackedWitnessIds: ["wit-001"],
    createdFrom: "raw table import",
    reviewStatus: "AI Pending Review",
  },
  {
    id: "case-002",
    caseName: "PARKER, JORDAN (PARKER, LENA INF)",
    normalizedCaseName: "PARKER, JORDAN",
    pca: "08F",
    venue: "Nassau",
    calendarCall: "02/04/2026",
    cm: "JKL",
    la: "MTR",
    ta: "SND",
    nextConf: "06/10/2026",
    div: "MM-BI",
    rawRowIds: ["raw-003"],
    trackedWitnessIds: ["wit-005"],
    createdFrom: "raw table import",
    reviewStatus: "AI Pending Review",
  },
];

export const ebtWitnesses = [
  {
    id: "wit-001",
    caseGroupId: "case-001",
    witnessName: "Dr. Alan Mercer",
    witnessType: "Defendant Doctor",
    relatedParty: "Dr. Alan Mercer",
    producingPartyId: "party-def-a",
    oobDate: "05/19/2026",
    lastFollowUpDate: "05/10/2026",
    firmDate: null,
    completedDate: null,
    isTracked: true,
    trackingStatus: "Tracked",
    possibleDates: ["06/09/2026", "06/12/2026"],
    status: "Needs Date",
    notes: "Busted EBT; needs new date.",
    reviewStatus: "AI Pending Review",
  },
  {
    id: "wit-002",
    caseGroupId: "case-001",
    witnessName: "Institutional Witness",
    witnessType: "Institutional Witness",
    relatedParty: "North County Medical Center",
    producingPartyId: "party-def-a",
    oobDate: "06/18/2026",
    lastFollowUpDate: "05/08/2026",
    firmDate: null,
    completedDate: null,
    isTracked: false,
    trackingStatus: "Available To Track",
    possibleDates: [],
    status: "Pending",
    notes: "Pending attorney confirmation.",
    reviewStatus: "AI Pending Review",
  },
  {
    id: "wit-003",
    caseGroupId: "case-001",
    witnessName: "Dr. Victoria Hale",
    witnessType: "Defendant Doctor",
    relatedParty: "Dr. Victoria Hale",
    producingPartyId: "party-def-b",
    oobDate: null,
    lastFollowUpDate: null,
    firmDate: null,
    completedDate: "04/17/2026",
    isTracked: false,
    trackingStatus: "Completed",
    possibleDates: [],
    status: "Completed",
    notes: "Completed.",
    reviewStatus: "Human Verified",
  },
  {
    id: "wit-004",
    caseGroupId: "case-001",
    witnessName: "Father Witness",
    witnessType: "Non-Party Witness",
    relatedParty: "Family Witness",
    producingPartyId: "party-plaintiff",
    oobDate: null,
    lastFollowUpDate: null,
    firmDate: null,
    completedDate: null,
    isTracked: false,
    trackingStatus: "Available To Track",
    possibleDates: [],
    status: "TBD",
    notes: "",
    reviewStatus: "AI Pending Review",
  },
  {
    id: "wit-005",
    caseGroupId: "case-002",
    witnessName: "Plaintiff Day 2",
    witnessType: "Plaintiff EBT",
    relatedParty: "Plaintiff",
    producingPartyId: "party-plaintiff-002",
    oobDate: "06/01/2026",
    lastFollowUpDate: "05/13/2026",
    firmDate: "05/21/2026",
    completedDate: null,
    isTracked: true,
    trackingStatus: "Tracked",
    possibleDates: ["05/21/2026", "05/29/2026", "06/04/2026"],
    status: "Firm",
    notes: "Confirm reporter/Zoom.",
    reviewStatus: "AI Pending Review",
  },
  {
    id: "wit-006",
    caseGroupId: "case-002",
    witnessName: "Dr. Iris Conway",
    witnessType: "Defendant Doctor",
    relatedParty: "Dr. Iris Conway",
    producingPartyId: "party-def-a-002",
    oobDate: "06/15/2026",
    lastFollowUpDate: "05/13/2026",
    firmDate: "06/09/2026",
    completedDate: null,
    isTracked: false,
    trackingStatus: "Available To Track",
    possibleDates: ["06/09/2026", "06/12/2026", "06/15/2026"],
    status: "Firm",
    notes: "",
    reviewStatus: "AI Pending Review",
  },
];

export const caseParties = [
  { id: "party-plaintiff", caseGroupId: "case-001", label: "Plaintiff", partyType: "Plaintiff Counsel", displayOrder: 1, lastReplyDate: "05/12/2026", replyStatus: "Responded", contactEmail: null, contactSource: "Manual Only" },
  { id: "party-def-a", caseGroupId: "case-001", label: "Def A", partyType: "Defense Counsel", displayOrder: 2, lastReplyDate: "05/10/2026", replyStatus: "Responded", contactEmail: null, contactSource: "Manual Only" },
  { id: "party-def-b", caseGroupId: "case-001", label: "Def B", partyType: "Defense Counsel", displayOrder: 3, lastReplyDate: "05/09/2026", replyStatus: "Responded", contactEmail: null, contactSource: "Manual Only" },
  { id: "party-def-d", caseGroupId: "case-001", label: "Def D", partyType: "Defense Counsel", displayOrder: 4, lastReplyDate: "05/10/2026", replyStatus: "No Dates Provided", contactEmail: null, contactSource: "Manual Only" },
  { id: "party-plaintiff-002", caseGroupId: "case-002", label: "Plaintiff", partyType: "Plaintiff Counsel", displayOrder: 1, lastReplyDate: "05/13/2026", replyStatus: "Responded", contactEmail: null, contactSource: "Manual Only" },
  { id: "party-def-a-002", caseGroupId: "case-002", label: "Def A", partyType: "Defense Counsel", displayOrder: 2, lastReplyDate: "05/12/2026", replyStatus: "Responded", contactEmail: null, contactSource: "Manual Only" },
];

export const witnessAvailability = [
  { id: "avail-001", caseGroupId: "case-001", witnessId: "wit-001", partyId: "party-plaintiff", availableDates: ["06/09/2026", "06/12/2026", "06/17/2026"], unavailableDates: [], lastUpdated: "05/12/2026", sourceType: "Email", updatedBy: "PB", notes: "", reviewStatus: "AI Pending Review" },
  { id: "avail-002", caseGroupId: "case-001", witnessId: "wit-001", partyId: "party-def-a", availableDates: ["06/04/2026", "06/09/2026", "06/12/2026"], unavailableDates: [], lastUpdated: "05/10/2026", sourceType: "Email", updatedBy: "PB", notes: "", reviewStatus: "AI Pending Review" },
  { id: "avail-003", caseGroupId: "case-001", witnessId: "wit-001", partyId: "party-def-b", availableDates: ["06/09/2026", "06/17/2026", "06/20/2026"], unavailableDates: ["06/04/2026", "06/15/2026"], lastUpdated: "05/09/2026", sourceType: "Email", updatedBy: "PB", notes: "", reviewStatus: "AI Pending Review" },
  { id: "avail-004", caseGroupId: "case-001", witnessId: "wit-001", partyId: "party-def-d", availableDates: [], unavailableDates: [], lastUpdated: "05/10/2026", sourceType: "Follow-Up", updatedBy: "PB", notes: "No dates provided.", reviewStatus: "AI Pending Review" },
  { id: "avail-005", caseGroupId: "case-002", witnessId: "wit-005", partyId: "party-plaintiff-002", availableDates: ["05/21/2026", "05/29/2026", "06/04/2026"], unavailableDates: [], lastUpdated: "05/13/2026", sourceType: "Internal Note", updatedBy: "JKL", notes: "", reviewStatus: "AI Pending Review" },
  { id: "avail-006", caseGroupId: "case-002", witnessId: "wit-005", partyId: "party-def-a-002", availableDates: ["05/21/2026", "06/03/2026"], unavailableDates: ["05/22/2026-05/28/2026"], lastUpdated: "05/12/2026", sourceType: "Email", updatedBy: "PB", notes: "", reviewStatus: "AI Pending Review" },
];

export const followUpLogs = [
  {
    id: "fu-001",
    caseGroupId: "case-001",
    witnessId: "wit-001",
    followUpDate: "05/10/2026",
    followUpType: "Email",
    sentBy: "PB",
    sentToPartyIds: ["party-def-a", "party-def-b", "party-def-d"],
    summary: "Requested new dates for Dr. Alan Mercer EBT.",
    result: "Partial responses received; Def D did not provide dates.",
    nextFollowUpDue: "05/23/2026",
    escalationNeeded: false,
    reviewStatus: "AI Pending Review",
  },
  {
    id: "fu-002",
    caseGroupId: "case-002",
    witnessId: "wit-005",
    followUpDate: "05/13/2026",
    followUpType: "Email",
    sentBy: "PB",
    sentToPartyIds: ["party-plaintiff-002", "party-def-a-002"],
    summary: "Confirmed plaintiff day 2 availability and asked for reporter confirmation.",
    result: "Pending reporter confirmation.",
    nextFollowUpDue: "05/20/2026",
    escalationNeeded: false,
    reviewStatus: "AI Pending Review",
  },
];
